apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: fastmcp-unified-binary
  namespace: mcp
spec:
  source:
    type: Binary
    binary: {}
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Containerfile
  output:
    to:
      kind: ImageStreamTag
      name: fastmcp-unified:latest
  triggers:
  - type: ConfigChange
