apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: fastmcp-unified
  namespace: mcp
spec:
  source:
    type: Git
    git:
      uri: https://example.com/your/repo.git
      ref: main
    contextDir: .
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Containerfile
  output:
    to:
      kind: ImageStreamTag
      name: fastmcp-unified:latest
  triggers:
  - type: ConfigChange
  - type: ImageChange
