apiVersion: v1
kind: ConfigMap
metadata:
  name: fastmcp-prompts
  namespace: mcp
  labels:
    app: fastmcp-unified

data:
  # You can inline prompts here for cluster-only deployments.
  summarize.yaml: |
    name: summarize
    description: Summarize a document with clear section markers.
    prompt: |
      Summarize the following text:
      <document>{document}</document>
      Use clear, concise language.
      <output_schema>{output_schema}</output_schema>
